[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "9.0.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "7.3.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.4.10"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.12.3"

[[constraint]]
  branch = "master"
  name = "github.com/skarademir/naturalsort"

[[constraint]]
  name = "github.com/vmware/govcloudair"
  version = "0.0.2"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "0.20.0"

[prune]
  go-tests = true
  unused-packages = true
